### ISSUE TITLE
SPM error

### ISSUE THREAD

**Issue by Cavidan998** [VakhoKontridze/VComponents#12]
![Screenshot 2024-08-02 at 09 09 31](https://github.com/user-attachments/assets/6b89d21b-c323-4926-a9d7-35e0e7154b9f)

Hi, i can't find solution for this problem. Does anybody face with this issue?

**Comment by VakhoKontridze** [comment]
Package has been using the following Swift settings for some time:

```swift
let swiftSettings: [SwiftSetting] = [
    .unsafeFlags([
        "-Xfrontend", "-debug-time-function-bodies",
        "-Xfrontend", "-debug-time-expression-type-checking",
        "-Xfrontend", "-warn-long-function-bodies=100",
        "-Xfrontend", "-warn-long-expression-type-checking=100"
    ])
]
```

Something must have gone wrong in XCode build system since the last update. I've removed the settings in the latest version, and the problem should be fixed.

Check out `6.0.8` and let me know if the issue persists.

**Comment by Cavidan998** [comment]
thanks so much
