### ISSUE TITLE
VTextField - onChange handler fired before value is committed

### ISSUE THREAD

**Issue by texasexile** [VakhoKontridze/VComponents#5]
I have a `VTextField` with an `onChange` handler where the bound `String `variable is always one key stroke behind the actual string value. In `UIKitTextFieldCoordinator.textFieldDidChange()` there's code to commit the text change before the `changeHandler` is called. However, `UIKitTextFieldRepresentable.commitText()` is called asynchronously and is executed after the change handler is called.

This code is all running on the main thread so is there a reason to wrap the commitText string assignment in a `DispatchQueue.main.async`?

If it has to be assigned asynchronously, the changeHandler should be run as a completion handler in the async closure.

**Comment by VakhoKontridze** [comment]
I have removed GCD from `commitText` all-together. Changes are now in 1.3.1.

Thank you for your feedback.
