### ISSUE TITLE
Bug When Presenting vAlert in UIHostingViewController 

### ISSUE THREAD

**Issue by eazydubs** [VakhoKontridze/VComponents#7]
#### Environment
- VComponents v4.0.4
- Xcode 14.3
- iOS 16.2

#### Description
I have a UIHostingViewController with a SwiftUI rootView, where the rootView calls `.vAlert()` and results in the following:

<img src="https://user-images.githubusercontent.com/130003928/232114631-6575dbcf-b670-4544-b649-d4d1a626d835.png" width=25% height=25%>

**Comment by VakhoKontridze** [comment]
Hi.

Thanks for valuable feedback.

Reported bug was actually from `VComponent`'s dependency, `VCore`. Essentialy, `translatesAutoresizingMaskIntoConstraints = false` was applied to hosting `UIHostingController` in [PresentationHostViewController](https://github.com/VakhoKontridze/VCore/blob/main/Sources/VCore/Services%20and%20Managers/Presentation%20Host/PresentationHostViewController.swift). Flag was unnecessary as no constraints were applied, but it broke modal frames.

Your issue can be reduced to the following:

```swift
import SwiftUI
import VComponents

class ViewController: UIViewController {
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        present(UIHostingController(rootView: ContentView()), animated: true)
    }
}

struct ContentView: View {
    @State private var isPresented: Bool = false
    
    var body: some View {
        Button("Present", action: { isPresented = true })
            .vAlert(
                id: "alert",
                isPresented: $isPresented,
                title: "Lorem Ipsum",
                message: "Lorem ipsum",
                actions: {
                    VAlertOKButton(action: {})
                }
            )
    }
}
```

With the latest patch, it should be fixed. Make sure to update to `VComponents` `4.0.5` and `VCore` `4.8.1`.

Let me know if the issue still exists.

**Comment by eazydubs** [comment]
The issue is resolved with the new version. Thanks for the quick follow up!
